FROM registry.access.redhat.com/hi/python:3.13-builder AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_PREFERENCE=only-system

COPY --from=ghcr.io/astral-sh/uv /uv /bin/uv

WORKDIR /app

ADD libs /app/libs
ADD services /app/services
ADD .python-version /app
ADD pyproject.toml /app
ADD uv.lock /app

RUN uv sync --frozen --no-dev --no-editable --directory services/virtual-assistant

FROM registry.access.redhat.com/hi/python:3.13
WORKDIR /app

# Copy the application from the builder
COPY --from=builder /app/services/virtual-assistant/src /app
COPY --from=builder /app/.venv /app/.venv

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

USER 1001
