---
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
    direction LR

    class App {

    }

    namespace Client {
        class AbstractClient {
            <<interface>>
        }

        class ConcreteClientHttp {
            +__init__(service_url, user_identity, platform_request)
        }

        class UserIdentity {
        }

        class PlatformRequest {

        }
    }

    class HttpSession {
        <<Library>>
    }

    namespace Services {
        class Service {
        }

        class ServiceResponse {

        }
    }

    namespace Routes {
        class Route {
            +call() RouteResponse
        }

        class RouteResponse {
            response: string
        }

        class RouteTemplate {

        }

    }

    namespace Testing {
        class TestClient {

        }

        class TestRoute {

        }

        class TestApp {

        }

    }

    App *-- "*" Route : Contains

    AbstractClient <|-- ConcreteClientHttp : Implements
    ConcreteClientHttp *-- UserIdentity
    ConcreteClientHttp *-- PlatformRequest

    PlatformRequest *-- HttpSession

    AbstractClient *-- Service
    Service *-- Route

    Service ..> ServiceResponse

    Route --> RouteTemplate
    Route ..> RouteResponse

    TestClient --> HttpSession : Mocks
    TestClient --> ConcreteClientHttp : Testee

    TestRoute --> AbstractClient : Mocks
    TestRoute --> Route : Testee

    TestApp --> App : Testee
