[project]
name = "watson_extension"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "common",
    "astro-virtual-assistant",
]

[tool.uv.sources]
common = { workspace = true }
astro-virtual-assistant = { workspace = true }
